import {
  AlarmClockCheck,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowUpRight,
  BadgeCheck,
  BadgeDollarSign,
  Banknote,
  Bell,
  BellRing,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  Calculator,
  Car,
  ChartColumn,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartPie,
  CircleDollarSign,
  CircleHelp,
  CirclePercent,
  Coffee,
  Coins,
  CreditCard,
  Gem,
  Gift,
  Goal,
  HandCoins,
  Heart,
  Home,
  House,
  Landmark,
  Laptop,
  Monitor,
  NotebookText,
  Percent,
  PiggyBank,
  Plane,
  Receipt,
  ScanBarcode,
  Send,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  Ticket,
  TrendingDown,
  TrendingUp,
  Wallet,
  WalletCards,
  WalletMinimal,
} from "lucide-react-native";

export const ACCOUNT_ICONS = [
  { name: "Wallet", Icon: Wallet },
  { name: "PiggyBank", Icon: PiggyBank },
  { name: "CreditCard", Icon: CreditCard },
  { name: "Banknote", Icon: Banknote },
  { name: "CircleDollarSign", Icon: CircleDollarSign },
  { name: "BadgeDollarSign", Icon: BadgeDollarSign },
  { name: "Coins", Icon: Coins },
  { name: "HandCoins", Icon: HandCoins },
  { name: "WalletCards", Icon: WalletCards },
  { name: "WalletMinimal", Icon: WalletMinimal },
  { name: "Landmark", Icon: Landmark },
  { name: "Building2", Icon: Building2 },
  { name: "House", Icon: House },
  { name: "Home", Icon: Home },
  { name: "BriefcaseBusiness", Icon: BriefcaseBusiness },
  { name: "Briefcase", Icon: Briefcase },
  { name: "ShoppingBag", Icon: ShoppingBag },
  { name: "ShoppingCart", Icon: ShoppingCart },
  { name: "Store", Icon: Store },
  { name: "Gift", Icon: Gift },
  { name: "Receipt", Icon: Receipt },
  { name: "Calculator", Icon: Calculator },
  { name: "ChartColumn", Icon: ChartColumn },
  { name: "ChartColumnIncreasing", Icon: ChartColumnIncreasing },
  { name: "ChartColumnDecreasing", Icon: ChartColumnDecreasing },
  { name: "ChartPie", Icon: ChartPie },
  { name: "TrendingUp", Icon: TrendingUp },
  { name: "TrendingDown", Icon: TrendingDown },
  { name: "ArrowUpRight", Icon: ArrowUpRight },
  { name: "ArrowDownRight", Icon: ArrowDownRight },
  { name: "ArrowUpLeft", Icon: ArrowUpLeft },
  { name: "ArrowDownLeft", Icon: ArrowDownLeft },
  { name: "Shield", Icon: Shield },
  { name: "BadgeCheck", Icon: BadgeCheck },
  { name: "Bell", Icon: Bell },
  { name: "BellRing", Icon: BellRing },
  { name: "BookOpen", Icon: BookOpen },
  { name: "NotebookText", Icon: NotebookText },
  { name: "Target", Icon: Target },
  { name: "Goal", Icon: Goal },
  { name: "Gem", Icon: Gem },
  { name: "Sparkles", Icon: Sparkles },
  { name: "CirclePercent", Icon: CirclePercent },
  { name: "Percent", Icon: Percent },
  { name: "CircleHelp", Icon: CircleHelp },
  { name: "AlarmClockCheck", Icon: AlarmClockCheck },
  { name: "Send", Icon: Send },
  { name: "ScanBarcode", Icon: ScanBarcode },
  { name: "Ticket", Icon: Ticket },
  { name: "Car", Icon: Car },
  { name: "Plane", Icon: Plane },
  { name: "Smartphone", Icon: Smartphone },
  { name: "Laptop", Icon: Laptop },
  { name: "Monitor", Icon: Monitor },
  { name: "Coffee", Icon: Coffee },
  { name: "Heart", Icon: Heart },
] as const;
